# -*- yaml -*-
# METABUILD GENERATED metaconf/metaconf.groovy + metaconf/project/build.yaml.tmpl -> atlasdb/atlasdb-cassandra-tests/build.yaml
meta:
  name: AtlasdbCassandraTests
  use_legacy_revision: true
  source_target_version: 1.8
  skip_dist: true
jars:
  -
    name: atlasdb-cassandra-tests-test
    src:
      - src/test/java
      - src/test/resources
    is_test: true
    ivy_conf: test
