# -*- yaml -*-
# METABUILD GENERATED metaconf/metaconf.groovy + metaconf/project/build.yaml.tmpl -> atlasdb/atlasdb-client/build.yaml
meta:
  name: AtlasdbClient
  use_legacy_revision: true
  source_target_version: 1.8
  skip_dist: true
jars:
  -
    name: atlasdb-client
    src:
      - src/main/java
