# -*- yaml -*-
# METABUILD GENERATED metaconf/metaconf.groovy + metaconf/project/build.yaml.tmpl -> atlasdb/lock-impl/build.yaml
meta:
  name: LockImpl
  use_legacy_revision: true
  source_target_version: 1.8
  skip_dist: true
jars:
  -
    name: lock-impl
    src:
      - src/main/java
  -
    name: lock-impl-test
    src:
      - src/test/java
    depends:
      - lock-impl
    is_test: true
    ivy_conf: test
