# -*- yaml -*-
# METABUILD GENERATED metaconf/metaconf.groovy + metaconf/project/build.yaml.tmpl -> atlasdb/leader-election-impl/build.yaml
meta:
  name: LeaderElectionImpl
  use_legacy_revision: true
  source_target_version: 1.8
  skip_dist: true
jars:
  -
    name: leader-election-impl
    src:
      - src/main/java
  -
    name: leader-election-impl-test
    src:
      - src/test/java
    depends:
      - leader-election-impl
    is_test: true
    ivy_conf: test
