# -*- yaml -*-
# METABUILD GENERATED metaconf/metaconf.groovy + metaconf/project/build.yaml.tmpl -> atlasdb/examples/profile-client-protobufs/build.yaml
meta:
  name: ProfileClientProtobufs
  use_legacy_revision: true
  source_target_version: 1.8
  skip_dist: true
jars:
  -
    name: profile-client-protobufs
    src:
      - src/main/java
  -
    name: profile-client-protobufs-test
    src:
      - src/test/java
    depends:
      - profile-client-protobufs
    is_test: true
    ivy_conf: test
