# -*- yaml -*-
# METABUILD GENERATED metaconf/metaconf.groovy + metaconf/project/build.yaml.tmpl -> atlasdb/examples/profile-client/build.yaml
meta:
  name: ProfileClient
  use_legacy_revision: true
  source_target_version: 1.8
  skip_dist: true
jars:
  -
    name: profile-client
    src:
      - src/main/java
  -
    name: profile-client-test
    src:
      - src/test/java
    depends:
      - profile-client
    is_test: true
    ivy_conf: test
