# -*- yaml -*-
# METABUILD GENERATED metaconf/metaconf.groovy + metaconf/project/build.yaml.tmpl -> atlasdb/atlasdb-server/build.yaml
meta:
  name: AtlasdbServer
  use_legacy_revision: true
  source_target_version: 1.8
  skip_dist: true
jars:
  -
    name: atlasdb-server
    src:
      - src/main/java
  -
    name: atlasdb-server-test
    src:
      - src/test/java
      - src/test/resources
    depends:
      - atlasdb-server
    is_test: true
    ivy_conf: test
