# -*- yaml -*-
# METABUILD GENERATED metaconf/metaconf.groovy + metaconf/project/build.yaml.tmpl -> atlasdb/lock-api/build.yaml
meta:
  name: LockApi
  use_legacy_revision: true
  source_target_version: 1.6
  skip_dist: true
jars:
  -
    name: lock-api
    src:
      - src/main/java
