# -*- yaml -*-
# METABUILD GENERATED metaconf/metaconf.groovy + metaconf/project/build.yaml.tmpl -> atlasdb/atlasdb-commons/build.yaml
meta:
  name: AtlasdbCommons
  use_legacy_revision: true
  source_target_version: 1.6
  skip_dist: true
jars:
  -
    name: atlasdb-commons
    src:
      - src/main/java
  -
    name: atlasdb-commons-test
    src:
      - src/test/java
    depends:
      - atlasdb-commons
    is_test: true
    ivy_conf: test
