version: "2"
services:
  cassandra:
    hostname: "cassandra"
    image: cassandra:2
    environment:
    - CASSANDRA_BROADCAST_ADDRESS=$HOSTNAME
    - CASSANDRA_START_RPC=true
    ports:
      - "9160:9160"
      - "7199:7199"
      - "9042:9042"

  timelock1:
    hostname: "timelock1"
    build: ..
    environment:
      - HOSTNAME=timelock1
    ports:
      - "3828"
    depends_on:
      - cassandra

  timelock2:
    hostname: "timelock2"
    build: ..
    environment:
      - HOSTNAME=timelock2
    ports:
      - "3828"
    depends_on:
      - cassandra

  timelock3:
    hostname: "timelock3"
    build: ..
    environment:
      - HOSTNAME=timelock3
    ports:
      - "3828"
    depends_on:
      - cassandra

