# -*- yaml -*-
# METABUILD GENERATED metaconf/metaconf.groovy + metaconf/project/build.yaml.tmpl -> atlasdb/leader-election-api-protobufs/build.yaml
meta:
  name: LeaderElectionApiProtobufs
  use_legacy_revision: true
  source_target_version: 1.8
  skip_dist: true
jars:
  -
    name: leader-election-api-protobufs
    src:
      - src/main/java
