# -*- yaml -*-
# METABUILD GENERATED metaconf/metaconf.groovy + metaconf/project/build.yaml.tmpl -> atlasdb/atlasdb-api/build.yaml
meta:
  name: AtlasdbApi
  use_legacy_revision: true
  source_target_version: 1.8
  skip_dist: true
jars:
  -
    name: atlasdb-api
    src:
      - src/main/java
